### ISSUE TITLE
All branches synced = workflow tsunami

### ISSUE THREAD

**Issue by cbrunnkvist** [actions/actions-sync#12]
When I `sync` a repo, all branches are get pulled. This means that all branches consequently get their `push` event triggered on the (GHES) destination side. For some repos this means you involuntarily/perhaps unknowingly set off potentially quite a large backlog of workflows - the repo I just synced contained ~50 branches, ~50 releases, and ~20 workflows, all `on: [push]`. I suppose I won't be using my workers for anything else for the rest of today... 😢 

**Ideas**
- _Would_ it make sense to only sync the _main branch_ by default?
- _Should_ there be some way to allow specifying "branches to sync, per repo-name" (i.e. extending the `upstream_org/upstream_repo:destination_org/dstination_repo` syntax)?

**Comment by andymckay** [comment]
Just trying to understand your use case. You are using actions-sync on a repository that itself has Actions on it? So in this case syncing the repo causes those Actions to trigger?

The original intent was the actions in the actions org on GitHub and by default none of those have workflows on them that will trigger, so this might not be a use case we've considered.

**Comment by ManuelMinkAtBOSCH** [comment]
i tried actions-sync for the first time today. great job 👍🏻 

but i also stumbled about this issue that all branches are synced.
When i got it right, the purpose of this tool is to only sync github.com actions to GHES.
So it should be sufficient, when the ghes branch of a workflow repo is synced, as it is the only branch which is used on ghes.
Also all workflow repos after appliance installation only have ghes branch available.


but after syncing a repo with actions-sync, all branches from github.com are available on GHES.

does it make sense to change this behavior or at least add an option to change it?
Would really appreciate it.

**Comment by sorekz** [comment]
Hi, this issue is kinda old but can I still hook onto it?

We recently switched to using the actions-sync from manually syncing with `git mirror`.
And the action really makes things easier and much faster.

Now we use the action not only for the `actions/*` but also for other user actions. But the same unpleasant thing applies to the `actions/*` actions: Whenever there is a new branch that one is synced and when it is deleted in the github.com repo that branch is not cleaned up. Even when the cache-dir is cleaned, it is not removed from the target GHES repo.

In our case all the dev branches are not needed and it would be enough to sync the main branch and tags. It would also help if the action cleans up all the old dev and dependabot branches that are already closed on the github.com repos but now pile up in our GHES target repos.
