### ISSUE TITLE
How could I synchronize an action repo which requires authentication?

### ISSUE THREAD

**Issue by michaeljia2021** [actions/actions-sync#42]
Hello, I want to synchronize an action from an organization to my self-hosted GitHub enterprise. This action repo requires authorization, how can I synchronize it? I don't find a place to set credential. 

./actions-sync sync --cache-dir "cache"  --destination-token "ghp_12345"   --destination-url "https://github.*****.cn"   --repo-name "***-Shared-Actions/Action_***:DevOps/Action_***"
pulling ***-Shared-Actions/Action_*** to cache/DevOps/Action_*** ...
could not pull  ***-Shared-Actions/Action_***, the repository may require authentication or does not exist

**Comment by ajaykn** [comment]
@michaeljia2021, currently action sync tool supports syncing public repositories.

If we want to sync the repos that needs credentials to pull, current workaround i can suggest:

Use push instead of `Sync`.
- Pull the codebase manually into the cache folder
While pulling, set your git credentials in your machine (just like how we pull private repos)
```code
git clone <url>
```
Once we have the repo source code under `cache` directory, then use the push command.
```code
bin/actions-sync push --cache-dir "cache" --destination-token "<token>" --destination-url "https://<ghes_instance>" --repo-name "actions/setup-node"
```

**Comment by michaeljia2021** [comment]
@ajaykn thanks for your help, it works now
